# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtTest
import random
import time

timings = []
CheckTime = False
initial = 0

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.Reflex = QtWidgets.QPushButton(self.centralwidget)
        self.Reflex.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.Reflex.setObjectName("Reflex")
        self.Reflex.setStyleSheet("background-color: #1a75ff; font-size : 100px")
        self.Reflex.clicked.connect(self.OnReflex)
        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Reflex.setText(_translate("MainWindow", "Click to start"))

    def OnReflex(self):
        final = time.time()
        
        global timings
        global CheckTime
        global initial

        if CheckTime == True:
            timings.append(round((final - initial) * 1000, 0))
            
        else:
            CheckTime = True


        if len(timings) == 5:
            self.Reflex.setObjectName("Reflex")
            self.Reflex.setStyleSheet("background-color: #1a75ff; font-size : 100px")
            self.Reflex.setText("You averaged " + str(int(round(sum(timings) / 5, 0))) + "ms\nClick to run again")
            
            CheckTime = False
            timings = []

        else:
            self.Reflex.setEnabled(False)
            self.Reflex.setStyleSheet("background-color: red; font-size : 100px")
            self.Reflex.setText("Wait until the screen turns green")
        
            QtTest.QTest.qWait(3000 + random.randint(0,200))
            initial = time.time()
        
            self.Reflex.setText("Click")
            self.Reflex.setStyleSheet("background-color: green; font-size : 100px")
            self.Reflex.setEnabled(True)
 

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
